#!/bin/bash
# This script is licensed under GPL V3 or higher
#
# Author: Angel Berlanas Vicente
#         angel.berlanas@gmail.com   
#
#

# Some values

host="eddie"
svndir="$HOME/svn/pandora/"
gitdir="$HOME/github/"


log_message()
{
  # Show log messages at fancy colours
  echo "[ Git <=> Svn ] : $1"
}

customize_values_by_hostname()
{
  # Get the hostname
  if [ $(hostname) = "$host" ] ; then
    log_message "The host is : $host"
    log_message "The subversion is : $svndir"
    log_message "The github is : $gitdir"
  fi
}

log_message "Who am I?"
customize_values_by_hostname
